<?php

namespace IW\EasySurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextQuestionOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextQuestionOptionRepository extends EntityRepository
{
}
