iw_easy_survey_homepage:
    pattern:  /EasySurvey/
    defaults: { _controller: IWEasySurveyBundle:Default:index }
    
iw_easy_survey_homepage2:
    pattern:  /
    defaults: { _controller: IWEasySurveyBundle:Default:index }

iw_easy_survey_contact:
    pattern:  /EasySurvey/contact
    defaults: { _controller: IWEasySurveyBundle:Default:contact }

iw_easy_survey_create_user:
    pattern: /EasySurvey/createUser
    defaults: { _controller: IWEasySurveyBundle:User:createUser }

iw_easy_survey_confirm_user:
    pattern: /EasySurvey/confirmUser
    defaults: { _controller: IWEasySurveyBundle:User:confirmUser }
    
iw_easy_survey_confirm_email:
    pattern: /EasySurvey/confirmEmailUser/{seeskey}/{username}
    defaults: { _controller: IWEasySurveyBundle:User:confirmEmailUser }

iw_easy_survey_modify_user:
    pattern: /EasySurvey/modifyUser
    defaults: { _controller: IWEasySurveyBundle:User:modifyUser }

iw_easy_survey_delete_user:
    pattern: /EasySurvey/deleteUser
    defaults: { _controller: IWEasySurveyBundle:User:deleteUser }

iw_easy_survey_login:
    pattern: /EasySurvey/login
    defaults: { _controller: IWEasySurveyBundle:User:login }

iw_easy_survey_logout:
    pattern: /EasySurvey/logout
    defaults: { _controller: IWEasySurveyBundle:User:logout }
    
iw_easy_survey_create_project:
    pattern: /EasySurvey/createProject
    defaults: { _controller: IWEasySurveyBundle:Project:create }
    
iw_easy_survey_manage_project:
    pattern: /EasySurvey/manageProject
    defaults: { _controller: IWEasySurveyBundle:Project:manage }
    
iw_easy_survey_edit_project:
    pattern: /EasySurvey/editProject/{id}
    defaults: { _controller: IWEasySurveyBundle:Project:edit }
    
iw_easy_survey_delete_project:
    pattern: /EasySurvey/deleteProject/{id}
    defaults: { _controller: IWEasySurveyBundle:Project:delete }
    
iw_easy_survey_create_quiz:
    pattern: /EasySurvey/createQuiz
    defaults: { _controller: IWEasySurveyBundle:Quiz:create }

iw_easy_survey_manage_quiz:
    pattern: /EasySurvey/manageQuiz/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:manage }

iw_easy_survey_edit_quiz:
    pattern: /EasySurvey/editQuiz/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:edit }
    
iw_easy_survey_delete_quiz:
    pattern: /EasySurvey/deleteQuiz/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:delete }
    
iw_easy_survey_manage_questions:
    pattern: /EasySurvey/manageQuestions/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:manageQuestions }
    
iw_easy_survey_add_question:
    pattern: /EasySurvey/addQuestion/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:addQuestion }
    
iw_easy_survey_edit_question:
    pattern: /EasySurvey/editQuestion/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:editQuestion }
    
iw_easy_survey_delete_question:
    pattern: /EasySurvey/deleteQuestion/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:deleteQuestion } 
    
iw_easy_survey_manage_question_option:
    pattern: /EasySurvey/manageQuestionOption/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:manageQuestionOption }
    
iw_easy_survey_edit_question_option:
    pattern: /EasySurvey/editQuestionOption/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:manageQuestionOption }
    
iw_easy_survey_edit_option:
    pattern: /EasySurvey/editOption/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:editOption }
    
iw_easy_survey_delete_option:
    pattern: /EasySurvey/deleteOption/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:deleteOption }
    
iw_easy_survey_add_option:
    pattern: /EasySurvey/addOption/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:addOption }
    
iw_easy_survey_instance_quiz:
    pattern: /EasySurvey/instanceQuiz/
    defaults: {_controller: IWEasySurveyBundle:Quiz:instance }
    
iw_easy_survey_generate_instance:
    pattern: /EasySurvey/generateInstanceQuiz/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:generateInstance }
    
iw_easy_survey_instances:
    pattern: /EasySurvey/instances/{idProject}/{idQuiz}
    defaults: {_controller: IWEasySurveyBundle:Quiz:instances }
    
iw_easy_survey_reply_quiz:
    pattern: /EasySurvey/replyQuiz/{seeskey}
    defaults: {_controller: IWEasySurveyBundle:Quiz:replyQuiz }   
    
iw_easy_survey_delete_instance:
    pattern: /EasySurvey/deleteInstance/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:deleteInstance }   
    
iw_easy_survey_collaborator:
    pattern: /EasySurvey/collaborator/{id}
    defaults: {_controller: IWEasySurveyBundle:Project:collaborator }   
    
iw_easy_survey_close_instance:
    pattern: /EasySurvey/closeInstance/{id}
    defaults: {_controller: IWEasySurveyBundle:Quiz:closeInstance }   
    
iw_easy_survey_results:
    pattern: /EasySurvey/resultInstance/{id}
    defaults: {_controller: IWEasySurveyBundle:Result:index }   
    
iw_easy_survey_generater_csv:
    pattern: /EasySurvey/generaterCsvInstance/{id}
    defaults: {_controller: IWEasySurveyBundle:Result:generateCsv }   

iw_easy_survey_show_data:
    pattern: /EasySurvey/showData/{id}
    defaults: {_controller: IWEasySurveyBundle:Result:showData }   
    
