iw_easy_survey_homepage:
    pattern:  /EasySurvey/
    defaults: { _controller: IWEasySurveyBundle:Default:index }

iw_easy_survey_contact:
    pattern:  /EasySurvey/contact
    defaults: { _controller: IWEasySurveyBundle:Default:contact }

iw_easy_survey_create_user:
    pattern: /EasySurvey/createUser
    defaults: { _controller: IWEasySurveyBundle:User:createUser }

iw_easy_survey_confirm_user:
    pattern: /EasySurvey/confirmUser
    defaults: { _controller: IWEasySurveyBundle:User:confirmUser }
    
iw_easy_survey_confirm_email:
    pattern: /EasySurvey/confirmEmailUser/{seeskey}/{username}
    defaults: { _controller: IWEasySurveyBundle:User:confirmEmailUser }

iw_easy_survey_modify_user:
    pattern: /EasySurvey/modifyUser
    defaults: { _controller: IWEasySurveyBundle:User:modifyUser }

iw_easy_survey_delete_user:
    pattern: /EasySurvey/deleteUser
    defaults: { _controller: IWEasySurveyBundle:User:deleteUser }

iw_easy_survey_login:
    pattern: /EasySurvey/login
    defaults: { _controller: IWEasySurveyBundle:User:login }

iw_easy_survey_logout:
    pattern: /EasySurvey/logout
    defaults: { _controller: IWEasySurveyBundle:User:logout }
    
iw_easy_survey_create_project:
    pattern: /EasySurvey/createProject
    defaults: { _controller: IWEasySurveyBundle:Project:create }
    
iw_easy_survey_manage_project:
    pattern: /EasySurvey/manageProject
    defaults: { _controller: IWEasySurveyBundle:Project:manage }
    
iw_easy_survey_edit_project:
    pattern: /EasySurvey/editProject/{id}
    defaults: { _controller: IWEasySurveyBundle:Project:edit }
    
iw_easy_survey_delete_project:
    pattern: /EasySurvey/deleteProject/{id}
    defaults: { _controller: IWEasySurveyBundle:Project:delete }
    
iw_easy_survey_create_quiz:
    pattern: /EasySurvey/createQuiz
    defaults: { _controller: IWEasySurveyBundle:Quiz:create }

iw_easy_survey_manage_quiz:
    pattern: /EasySurvey/manageQuiz
    defaults: { _controller: IWEasySurveyBundle:Quiz:manage }

iw_easy_survey_edit_quiz:
    pattern: /EasySurvey/editQuiz/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:edit }
    
iw_easy_survey_delete_quiz:
    pattern: /EasySurvey/deleteQuiz/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:delete }
    
iw_easy_survey_manage_questions:
    pattern: /EasySurvey/manageQuestions/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:manageQuestions }
    
iw_easy_survey_add_question:
    pattern: /EasySurvey/addQuestion/{id}
    defaults: { _controller: IWEasySurveyBundle:Quiz:addQuestion }