IW\EasySurveyBundle\Entity\Quiz:
    type: entity
    table: null
    repositoryClass: IW\EasySurveyBundle\Entity\QuizRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        projectId:
            type: integer
            column: project_id
            
    lifecycleCallbacks: {  }
