IW\EasySurveyBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: IW\EasySurveyBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        email:
            type: string
            length: 255
        confirm:
            type: boolean
        sesskeyConfirm:
            type: string
            length: 255
            
    lifecycleCallbacks: {  }
