IW\EasySurveyBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: IW\EasySurveyBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '255'
        password:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
