parameters:
#    ahvegahome.example.class: Ahvega\HomeBundle\Example

services:
#    ahvegahome.example:
#        class: %ahvegahome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
